name: mr_collection
description: "集金くん"
publish_to: 'none'

version: 1.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  path_provider: ^2.0.11
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.1.10
  flutter_line_sdk: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  ios: true
  image_path: "assets/icons/icon.png"


flutter:
  assets: 
    - assets/images/loading_image.svg
    - assets/icons/filter.svg
    - assets/icons/circle_plus.svg
    - assets/icons/settings.svg
    - assets/icons/flag.svg
    - assets/icons/sad_face.svg
    - assets/icons/close_circle.svg
    - assets/icons/check_circle.svg
    - assets/icons/line.svg
    - assets/icons/delete.svg
    - assets/icons/plus.svg
    - assets/icons/line-login.svg
    - assets/icons/apple_logo.svg
    - assets/icons/sort.svg
    - assets/icons/user-add.svg
    - assets/icons/chat_bubble.svg
    - assets/icons/yen.svg
    - assets/icons/drawer_yen.svg
    - assets/icons/drawer_star.svg
    - assets/icons/drawer_key.svg
    - assets/icons/drawer_file.svg
    - assets/icons/drawer_delete_account.svg

  uses-material-design: true
